// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.0
// source: tools.proto

package toolsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_tools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_tools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ProcessDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ToolType      string                 `protobuf:"bytes,2,opt,name=tool_type,json=toolType,proto3" json:"tool_type,omitempty"` // "classification", "sentiment", "extraction"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessDataRequest) Reset() {
	*x = ProcessDataRequest{}
	mi := &file_tools_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDataRequest) ProtoMessage() {}

func (x *ProcessDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDataRequest.ProtoReflect.Descriptor instead.
func (*ProcessDataRequest) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessDataRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ProcessDataRequest) GetToolType() string {
	if x != nil {
		return x.ToolType
	}
	return ""
}

type ProcessDataResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Result           string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Confidence       float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ProcessingTimeMs int64                  `protobuf:"varint,3,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProcessDataResponse) Reset() {
	*x = ProcessDataResponse{}
	mi := &file_tools_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDataResponse) ProtoMessage() {}

func (x *ProcessDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tools_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDataResponse.ProtoReflect.Descriptor instead.
func (*ProcessDataResponse) Descriptor() ([]byte, []int) {
	return file_tools_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessDataResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ProcessDataResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ProcessDataResponse) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

var File_tools_proto protoreflect.FileDescriptor

const file_tools_proto_rawDesc = "" +
	"\n" +
	"\vtools.proto\x12\btools.v1\"\x0f\n" +
	"\rHealthRequest\"\\\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"E\n" +
	"\x12ProcessDataRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x1b\n" +
	"\ttool_type\x18\x02 \x01(\tR\btoolType\"{\n" +
	"\x13ProcessDataResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12,\n" +
	"\x12processing_time_ms\x18\x03 \x01(\x03R\x10processingTimeMs2\x97\x01\n" +
	"\fToolsService\x12;\n" +
	"\x06Health\x12\x17.tools.v1.HealthRequest\x1a\x18.tools.v1.HealthResponse\x12J\n" +
	"\vProcessData\x12\x1c.tools.v1.ProcessDataRequest\x1a\x1d.tools.v1.ProcessDataResponseB2Z0github.com/0xsj/scout/api/proto/tools/v1;toolsv1b\x06proto3"

var (
	file_tools_proto_rawDescOnce sync.Once
	file_tools_proto_rawDescData []byte
)

func file_tools_proto_rawDescGZIP() []byte {
	file_tools_proto_rawDescOnce.Do(func() {
		file_tools_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tools_proto_rawDesc), len(file_tools_proto_rawDesc)))
	})
	return file_tools_proto_rawDescData
}

var file_tools_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tools_proto_goTypes = []any{
	(*HealthRequest)(nil),       // 0: tools.v1.HealthRequest
	(*HealthResponse)(nil),      // 1: tools.v1.HealthResponse
	(*ProcessDataRequest)(nil),  // 2: tools.v1.ProcessDataRequest
	(*ProcessDataResponse)(nil), // 3: tools.v1.ProcessDataResponse
}
var file_tools_proto_depIdxs = []int32{
	0, // 0: tools.v1.ToolsService.Health:input_type -> tools.v1.HealthRequest
	2, // 1: tools.v1.ToolsService.ProcessData:input_type -> tools.v1.ProcessDataRequest
	1, // 2: tools.v1.ToolsService.Health:output_type -> tools.v1.HealthResponse
	3, // 3: tools.v1.ToolsService.ProcessData:output_type -> tools.v1.ProcessDataResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tools_proto_init() }
func file_tools_proto_init() {
	if File_tools_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tools_proto_rawDesc), len(file_tools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tools_proto_goTypes,
		DependencyIndexes: file_tools_proto_depIdxs,
		MessageInfos:      file_tools_proto_msgTypes,
	}.Build()
	File_tools_proto = out.File
	file_tools_proto_goTypes = nil
	file_tools_proto_depIdxs = nil
}
