apiVersion: v1
kind: Service
metadata:
  name: agents
  namespace: scout
  labels:
    app: agents
spec:
  type: NodePort
  selector:
    app: agents
    component: server
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081
      protocol: TCP