// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: incidents.proto

package incidentsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IncidentsService_Health_FullMethodName             = "/incidents.v1.IncidentsService/Health"
	IncidentsService_GetIncidentSummary_FullMethodName = "/incidents.v1.IncidentsService/GetIncidentSummary"
)

// IncidentsServiceClient is the client API for IncidentsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IncidentsService provides incident management operations
type IncidentsServiceClient interface {
	// Health checks if the service is healthy
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// GetIncidentSummary returns a summary of current incidents
	GetIncidentSummary(ctx context.Context, in *GetIncidentSummaryRequest, opts ...grpc.CallOption) (*GetIncidentSummaryResponse, error)
}

type incidentsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIncidentsServiceClient(cc grpc.ClientConnInterface) IncidentsServiceClient {
	return &incidentsServiceClient{cc}
}

func (c *incidentsServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, IncidentsService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *incidentsServiceClient) GetIncidentSummary(ctx context.Context, in *GetIncidentSummaryRequest, opts ...grpc.CallOption) (*GetIncidentSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIncidentSummaryResponse)
	err := c.cc.Invoke(ctx, IncidentsService_GetIncidentSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IncidentsServiceServer is the server API for IncidentsService service.
// All implementations must embed UnimplementedIncidentsServiceServer
// for forward compatibility.
//
// IncidentsService provides incident management operations
type IncidentsServiceServer interface {
	// Health checks if the service is healthy
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// GetIncidentSummary returns a summary of current incidents
	GetIncidentSummary(context.Context, *GetIncidentSummaryRequest) (*GetIncidentSummaryResponse, error)
	mustEmbedUnimplementedIncidentsServiceServer()
}

// UnimplementedIncidentsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIncidentsServiceServer struct{}

func (UnimplementedIncidentsServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedIncidentsServiceServer) GetIncidentSummary(context.Context, *GetIncidentSummaryRequest) (*GetIncidentSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIncidentSummary not implemented")
}
func (UnimplementedIncidentsServiceServer) mustEmbedUnimplementedIncidentsServiceServer() {}
func (UnimplementedIncidentsServiceServer) testEmbeddedByValue()                          {}

// UnsafeIncidentsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IncidentsServiceServer will
// result in compilation errors.
type UnsafeIncidentsServiceServer interface {
	mustEmbedUnimplementedIncidentsServiceServer()
}

func RegisterIncidentsServiceServer(s grpc.ServiceRegistrar, srv IncidentsServiceServer) {
	// If the following call pancis, it indicates UnimplementedIncidentsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IncidentsService_ServiceDesc, srv)
}

func _IncidentsService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncidentsServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IncidentsService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncidentsServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IncidentsService_GetIncidentSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIncidentSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncidentsServiceServer).GetIncidentSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IncidentsService_GetIncidentSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncidentsServiceServer).GetIncidentSummary(ctx, req.(*GetIncidentSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IncidentsService_ServiceDesc is the grpc.ServiceDesc for IncidentsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IncidentsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "incidents.v1.IncidentsService",
	HandlerType: (*IncidentsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _IncidentsService_Health_Handler,
		},
		{
			MethodName: "GetIncidentSummary",
			Handler:    _IncidentsService_GetIncidentSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "incidents.proto",
}
