// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.0
// source: incidents.proto

package incidentsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_incidents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_incidents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_incidents_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_incidents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_incidents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_incidents_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetIncidentSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIncidentSummaryRequest) Reset() {
	*x = GetIncidentSummaryRequest{}
	mi := &file_incidents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIncidentSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncidentSummaryRequest) ProtoMessage() {}

func (x *GetIncidentSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_incidents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncidentSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetIncidentSummaryRequest) Descriptor() ([]byte, []int) {
	return file_incidents_proto_rawDescGZIP(), []int{2}
}

type GetIncidentSummaryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalIncidents int32                  `protobuf:"varint,1,opt,name=total_incidents,json=totalIncidents,proto3" json:"total_incidents,omitempty"`
	CriticalCount  int32                  `protobuf:"varint,2,opt,name=critical_count,json=criticalCount,proto3" json:"critical_count,omitempty"`
	ActiveCount    int32                  `protobuf:"varint,3,opt,name=active_count,json=activeCount,proto3" json:"active_count,omitempty"`
	ResolvedCount  int32                  `protobuf:"varint,4,opt,name=resolved_count,json=resolvedCount,proto3" json:"resolved_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetIncidentSummaryResponse) Reset() {
	*x = GetIncidentSummaryResponse{}
	mi := &file_incidents_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIncidentSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncidentSummaryResponse) ProtoMessage() {}

func (x *GetIncidentSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_incidents_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncidentSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetIncidentSummaryResponse) Descriptor() ([]byte, []int) {
	return file_incidents_proto_rawDescGZIP(), []int{3}
}

func (x *GetIncidentSummaryResponse) GetTotalIncidents() int32 {
	if x != nil {
		return x.TotalIncidents
	}
	return 0
}

func (x *GetIncidentSummaryResponse) GetCriticalCount() int32 {
	if x != nil {
		return x.CriticalCount
	}
	return 0
}

func (x *GetIncidentSummaryResponse) GetActiveCount() int32 {
	if x != nil {
		return x.ActiveCount
	}
	return 0
}

func (x *GetIncidentSummaryResponse) GetResolvedCount() int32 {
	if x != nil {
		return x.ResolvedCount
	}
	return 0
}

var File_incidents_proto protoreflect.FileDescriptor

const file_incidents_proto_rawDesc = "" +
	"\n" +
	"\x0fincidents.proto\x12\fincidents.v1\"\x0f\n" +
	"\rHealthRequest\"\\\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x1b\n" +
	"\x19GetIncidentSummaryRequest\"\xb6\x01\n" +
	"\x1aGetIncidentSummaryResponse\x12'\n" +
	"\x0ftotal_incidents\x18\x01 \x01(\x05R\x0etotalIncidents\x12%\n" +
	"\x0ecritical_count\x18\x02 \x01(\x05R\rcriticalCount\x12!\n" +
	"\factive_count\x18\x03 \x01(\x05R\vactiveCount\x12%\n" +
	"\x0eresolved_count\x18\x04 \x01(\x05R\rresolvedCount2\xc0\x01\n" +
	"\x10IncidentsService\x12C\n" +
	"\x06Health\x12\x1b.incidents.v1.HealthRequest\x1a\x1c.incidents.v1.HealthResponse\x12g\n" +
	"\x12GetIncidentSummary\x12'.incidents.v1.GetIncidentSummaryRequest\x1a(.incidents.v1.GetIncidentSummaryResponseB:Z8github.com/0xsj/scout/api/proto/incidents/v1;incidentsv1b\x06proto3"

var (
	file_incidents_proto_rawDescOnce sync.Once
	file_incidents_proto_rawDescData []byte
)

func file_incidents_proto_rawDescGZIP() []byte {
	file_incidents_proto_rawDescOnce.Do(func() {
		file_incidents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_incidents_proto_rawDesc), len(file_incidents_proto_rawDesc)))
	})
	return file_incidents_proto_rawDescData
}

var file_incidents_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_incidents_proto_goTypes = []any{
	(*HealthRequest)(nil),              // 0: incidents.v1.HealthRequest
	(*HealthResponse)(nil),             // 1: incidents.v1.HealthResponse
	(*GetIncidentSummaryRequest)(nil),  // 2: incidents.v1.GetIncidentSummaryRequest
	(*GetIncidentSummaryResponse)(nil), // 3: incidents.v1.GetIncidentSummaryResponse
}
var file_incidents_proto_depIdxs = []int32{
	0, // 0: incidents.v1.IncidentsService.Health:input_type -> incidents.v1.HealthRequest
	2, // 1: incidents.v1.IncidentsService.GetIncidentSummary:input_type -> incidents.v1.GetIncidentSummaryRequest
	1, // 2: incidents.v1.IncidentsService.Health:output_type -> incidents.v1.HealthResponse
	3, // 3: incidents.v1.IncidentsService.GetIncidentSummary:output_type -> incidents.v1.GetIncidentSummaryResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_incidents_proto_init() }
func file_incidents_proto_init() {
	if File_incidents_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_incidents_proto_rawDesc), len(file_incidents_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_incidents_proto_goTypes,
		DependencyIndexes: file_incidents_proto_depIdxs,
		MessageInfos:      file_incidents_proto_msgTypes,
	}.Build()
	File_incidents_proto = out.File
	file_incidents_proto_goTypes = nil
	file_incidents_proto_depIdxs = nil
}
