apiVersion: v1
kind: Service
metadata:
  name: analytics
  namespace: scout
  labels:
    app: analytics
spec:
  type: NodePort
  selector:
    app: analytics
    component: worker
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      nodePort: 30084
      protocol: TCP