# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tools.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tools.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btools.proto\x12\x08tools.v1\"\x0f\n\rHealthRequest\"B\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\"5\n\x12ProcessDataRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x11\n\ttool_type\x18\x02 \x01(\t\"U\n\x13ProcessDataResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x1a\n\x12processing_time_ms\x18\x03 \x01(\x03\x32\x97\x01\n\x0cToolsService\x12;\n\x06Health\x12\x17.tools.v1.HealthRequest\x1a\x18.tools.v1.HealthResponse\x12J\n\x0bProcessData\x12\x1c.tools.v1.ProcessDataRequest\x1a\x1d.tools.v1.ProcessDataResponseB2Z0github.com/0xsj/scout/api/proto/tools/v1;toolsv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tools_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/0xsj/scout/api/proto/tools/v1;toolsv1'
  _globals['_HEALTHREQUEST']._serialized_start=25
  _globals['_HEALTHREQUEST']._serialized_end=40
  _globals['_HEALTHRESPONSE']._serialized_start=42
  _globals['_HEALTHRESPONSE']._serialized_end=108
  _globals['_PROCESSDATAREQUEST']._serialized_start=110
  _globals['_PROCESSDATAREQUEST']._serialized_end=163
  _globals['_PROCESSDATARESPONSE']._serialized_start=165
  _globals['_PROCESSDATARESPONSE']._serialized_end=250
  _globals['_TOOLSSERVICE']._serialized_start=253
  _globals['_TOOLSSERVICE']._serialized_end=404
# @@protoc_insertion_point(module_scope)
