# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import tools_pb2 as tools__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tools_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ToolsServiceStub(object):
    """ToolsService provides ML tools operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/tools.v1.ToolsService/Health',
                request_serializer=tools__pb2.HealthRequest.SerializeToString,
                response_deserializer=tools__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ProcessData = channel.unary_unary(
                '/tools.v1.ToolsService/ProcessData',
                request_serializer=tools__pb2.ProcessDataRequest.SerializeToString,
                response_deserializer=tools__pb2.ProcessDataResponse.FromString,
                _registered_method=True)


class ToolsServiceServicer(object):
    """ToolsService provides ML tools operations
    """

    def Health(self, request, context):
        """Health checks if the service is healthy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessData(self, request, context):
        """ProcessData processes input data using ML tools
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToolsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=tools__pb2.HealthRequest.FromString,
                    response_serializer=tools__pb2.HealthResponse.SerializeToString,
            ),
            'ProcessData': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessData,
                    request_deserializer=tools__pb2.ProcessDataRequest.FromString,
                    response_serializer=tools__pb2.ProcessDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tools.v1.ToolsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tools.v1.ToolsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToolsService(object):
    """ToolsService provides ML tools operations
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tools.v1.ToolsService/Health',
            tools__pb2.HealthRequest.SerializeToString,
            tools__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tools.v1.ToolsService/ProcessData',
            tools__pb2.ProcessDataRequest.SerializeToString,
            tools__pb2.ProcessDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
