// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingest_records.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIngestRecords = `-- name: CountIngestRecords :one
SELECT COUNT(*) FROM ingest_records
WHERE 
    ($1::varchar IS NULL OR tenant_id = $1)
    AND ($2::varchar IS NULL OR source_id = $2)
    AND ($3::varchar IS NULL OR source_type = $3)
    AND ($4::ingest_status IS NULL OR status = $4)
    AND ($5::varchar IS NULL OR entity_type = $5)
    AND ($6::timestamptz IS NULL OR received_at >= $6)
    AND ($7::timestamptz IS NULL OR received_at <= $7)
`

type CountIngestRecordsParams struct {
	TenantID   pgtype.Text        `json:"tenant_id"`
	SourceID   pgtype.Text        `json:"source_id"`
	SourceType pgtype.Text        `json:"source_type"`
	Status     NullIngestStatus   `json:"status"`
	EntityType pgtype.Text        `json:"entity_type"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) CountIngestRecords(ctx context.Context, arg CountIngestRecordsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIngestRecords,
		arg.TenantID,
		arg.SourceID,
		arg.SourceType,
		arg.Status,
		arg.EntityType,
		arg.StartTime,
		arg.EndTime,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIngestRecord = `-- name: CreateIngestRecord :exec
INSERT INTO ingest_records (
    id, tenant_id, source_id, source_type, raw_data_id,
    status,
    validation_valid, validation_schema_valid, validation_fields_present, 
    validation_fields_missing, validation_anomalies, validation_validator_version,
    confidence_overall, confidence_source_reliability, confidence_data_completeness,
    confidence_temporal_freshness, confidence_signature_trust, confidence_factors,
    entity_type, entity_id, event_ids,
    rejection_reason, quarantine_id,
    source_signer, collector_signer, ingest_signer,
    source_signature_verified, collector_signature_verified,
    received_at, processed_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18,
    $19, $20, $21,
    $22, $23,
    $24, $25, $26,
    $27, $28,
    $29, $30
)
`

type CreateIngestRecordParams struct {
	ID                          string      `json:"id"`
	TenantID                    pgtype.Text `json:"tenant_id"`
	SourceID                    string      `json:"source_id"`
	SourceType                  string      `json:"source_type"`
	RawDataID                   string      `json:"raw_data_id"`
	Status                      string      `json:"status"`
	ValidationValid             bool        `json:"validation_valid"`
	ValidationSchemaValid       bool        `json:"validation_schema_valid"`
	ValidationFieldsPresent     []string    `json:"validation_fields_present"`
	ValidationFieldsMissing     []string    `json:"validation_fields_missing"`
	ValidationAnomalies         []byte      `json:"validation_anomalies"`
	ValidationValidatorVersion  pgtype.Text `json:"validation_validator_version"`
	ConfidenceOverall           float32     `json:"confidence_overall"`
	ConfidenceSourceReliability float32     `json:"confidence_source_reliability"`
	ConfidenceDataCompleteness  float32     `json:"confidence_data_completeness"`
	ConfidenceTemporalFreshness float32     `json:"confidence_temporal_freshness"`
	ConfidenceSignatureTrust    float32     `json:"confidence_signature_trust"`
	ConfidenceFactors           []byte      `json:"confidence_factors"`
	EntityType                  pgtype.Text `json:"entity_type"`
	EntityID                    pgtype.Text `json:"entity_id"`
	EventIds                    []string    `json:"event_ids"`
	RejectionReason             pgtype.Text `json:"rejection_reason"`
	QuarantineID                pgtype.Text `json:"quarantine_id"`
	SourceSigner                []byte      `json:"source_signer"`
	CollectorSigner             []byte      `json:"collector_signer"`
	IngestSigner                []byte      `json:"ingest_signer"`
	SourceSignatureVerified     pgtype.Bool `json:"source_signature_verified"`
	CollectorSignatureVerified  pgtype.Bool `json:"collector_signature_verified"`
	ReceivedAt                  time.Time   `json:"received_at"`
	ProcessedAt                 time.Time   `json:"processed_at"`
}

func (q *Queries) CreateIngestRecord(ctx context.Context, arg CreateIngestRecordParams) error {
	_, err := q.db.Exec(ctx, createIngestRecord,
		arg.ID,
		arg.TenantID,
		arg.SourceID,
		arg.SourceType,
		arg.RawDataID,
		arg.Status,
		arg.ValidationValid,
		arg.ValidationSchemaValid,
		arg.ValidationFieldsPresent,
		arg.ValidationFieldsMissing,
		arg.ValidationAnomalies,
		arg.ValidationValidatorVersion,
		arg.ConfidenceOverall,
		arg.ConfidenceSourceReliability,
		arg.ConfidenceDataCompleteness,
		arg.ConfidenceTemporalFreshness,
		arg.ConfidenceSignatureTrust,
		arg.ConfidenceFactors,
		arg.EntityType,
		arg.EntityID,
		arg.EventIds,
		arg.RejectionReason,
		arg.QuarantineID,
		arg.SourceSigner,
		arg.CollectorSigner,
		arg.IngestSigner,
		arg.SourceSignatureVerified,
		arg.CollectorSignatureVerified,
		arg.ReceivedAt,
		arg.ProcessedAt,
	)
	return err
}

const deleteIngestRecord = `-- name: DeleteIngestRecord :exec
DELETE FROM ingest_records WHERE id = $1
`

func (q *Queries) DeleteIngestRecord(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteIngestRecord, id)
	return err
}

const findIngestRecordByID = `-- name: FindIngestRecordByID :one
SELECT id, tenant_id, source_id, source_type, raw_data_id, status, validation_valid, validation_schema_valid, validation_fields_present, validation_fields_missing, validation_anomalies, validation_validator_version, confidence_overall, confidence_source_reliability, confidence_data_completeness, confidence_temporal_freshness, confidence_signature_trust, confidence_factors, entity_type, entity_id, event_ids, rejection_reason, quarantine_id, source_signer, collector_signer, ingest_signer, source_signature_verified, collector_signature_verified, received_at, processed_at, created_at FROM ingest_records WHERE id = $1
`

func (q *Queries) FindIngestRecordByID(ctx context.Context, id string) (IngestRecord, error) {
	row := q.db.QueryRow(ctx, findIngestRecordByID, id)
	var i IngestRecord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceID,
		&i.SourceType,
		&i.RawDataID,
		&i.Status,
		&i.ValidationValid,
		&i.ValidationSchemaValid,
		&i.ValidationFieldsPresent,
		&i.ValidationFieldsMissing,
		&i.ValidationAnomalies,
		&i.ValidationValidatorVersion,
		&i.ConfidenceOverall,
		&i.ConfidenceSourceReliability,
		&i.ConfidenceDataCompleteness,
		&i.ConfidenceTemporalFreshness,
		&i.ConfidenceSignatureTrust,
		&i.ConfidenceFactors,
		&i.EntityType,
		&i.EntityID,
		&i.EventIds,
		&i.RejectionReason,
		&i.QuarantineID,
		&i.SourceSigner,
		&i.CollectorSigner,
		&i.IngestSigner,
		&i.SourceSignatureVerified,
		&i.CollectorSignatureVerified,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findIngestRecordByRawDataID = `-- name: FindIngestRecordByRawDataID :one
SELECT id, tenant_id, source_id, source_type, raw_data_id, status, validation_valid, validation_schema_valid, validation_fields_present, validation_fields_missing, validation_anomalies, validation_validator_version, confidence_overall, confidence_source_reliability, confidence_data_completeness, confidence_temporal_freshness, confidence_signature_trust, confidence_factors, entity_type, entity_id, event_ids, rejection_reason, quarantine_id, source_signer, collector_signer, ingest_signer, source_signature_verified, collector_signature_verified, received_at, processed_at, created_at FROM ingest_records WHERE raw_data_id = $1
`

func (q *Queries) FindIngestRecordByRawDataID(ctx context.Context, rawDataID string) (IngestRecord, error) {
	row := q.db.QueryRow(ctx, findIngestRecordByRawDataID, rawDataID)
	var i IngestRecord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceID,
		&i.SourceType,
		&i.RawDataID,
		&i.Status,
		&i.ValidationValid,
		&i.ValidationSchemaValid,
		&i.ValidationFieldsPresent,
		&i.ValidationFieldsMissing,
		&i.ValidationAnomalies,
		&i.ValidationValidatorVersion,
		&i.ConfidenceOverall,
		&i.ConfidenceSourceReliability,
		&i.ConfidenceDataCompleteness,
		&i.ConfidenceTemporalFreshness,
		&i.ConfidenceSignatureTrust,
		&i.ConfidenceFactors,
		&i.EntityType,
		&i.EntityID,
		&i.EventIds,
		&i.RejectionReason,
		&i.QuarantineID,
		&i.SourceSigner,
		&i.CollectorSigner,
		&i.IngestSigner,
		&i.SourceSignatureVerified,
		&i.CollectorSignatureVerified,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getIngestStats = `-- name: GetIngestStats :one
SELECT
    COUNT(*) AS total_records,
    COUNT(*) FILTER (WHERE status = 'accepted') AS accepted_records,
    COUNT(*) FILTER (WHERE status = 'rejected') AS rejected_records,
    COUNT(*) FILTER (WHERE status = 'quarantined') AS quarantined_records,
    COUNT(*) FILTER (WHERE status = 'pending') AS pending_records,
    COALESCE(AVG(confidence_overall), 0)::real AS average_confidence,
    COUNT(*) FILTER (WHERE source_signature_verified = true) AS source_signatures_verified,
    COUNT(*) FILTER (WHERE source_signature_verified = false) AS source_signatures_failed,
    COUNT(*) FILTER (WHERE collector_signature_verified = true) AS collector_signatures_verified,
    COUNT(*) FILTER (WHERE collector_signature_verified = false) AS collector_signatures_failed
FROM ingest_records
WHERE 
    ($1::varchar IS NULL OR tenant_id = $1)
    AND ($2::varchar IS NULL OR source_id = $2)
    AND ($3::varchar IS NULL OR source_type = $3)
    AND ($4::timestamptz IS NULL OR received_at >= $4)
    AND ($5::timestamptz IS NULL OR received_at <= $5)
`

type GetIngestStatsParams struct {
	TenantID   pgtype.Text        `json:"tenant_id"`
	SourceID   pgtype.Text        `json:"source_id"`
	SourceType pgtype.Text        `json:"source_type"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

type GetIngestStatsRow struct {
	TotalRecords                int64   `json:"total_records"`
	AcceptedRecords             int64   `json:"accepted_records"`
	RejectedRecords             int64   `json:"rejected_records"`
	QuarantinedRecords          int64   `json:"quarantined_records"`
	PendingRecords              int64   `json:"pending_records"`
	AverageConfidence           float32 `json:"average_confidence"`
	SourceSignaturesVerified    int64   `json:"source_signatures_verified"`
	SourceSignaturesFailed      int64   `json:"source_signatures_failed"`
	CollectorSignaturesVerified int64   `json:"collector_signatures_verified"`
	CollectorSignaturesFailed   int64   `json:"collector_signatures_failed"`
}

func (q *Queries) GetIngestStats(ctx context.Context, arg GetIngestStatsParams) (GetIngestStatsRow, error) {
	row := q.db.QueryRow(ctx, getIngestStats,
		arg.TenantID,
		arg.SourceID,
		arg.SourceType,
		arg.StartTime,
		arg.EndTime,
	)
	var i GetIngestStatsRow
	err := row.Scan(
		&i.TotalRecords,
		&i.AcceptedRecords,
		&i.RejectedRecords,
		&i.QuarantinedRecords,
		&i.PendingRecords,
		&i.AverageConfidence,
		&i.SourceSignaturesVerified,
		&i.SourceSignaturesFailed,
		&i.CollectorSignaturesVerified,
		&i.CollectorSignaturesFailed,
	)
	return i, err
}

const getRecordsByEntityType = `-- name: GetRecordsByEntityType :many
SELECT entity_type, COUNT(*) AS count
FROM ingest_records
WHERE 
    entity_type IS NOT NULL
    AND ($1::varchar IS NULL OR tenant_id = $1)
    AND ($2::timestamptz IS NULL OR received_at >= $2)
    AND ($3::timestamptz IS NULL OR received_at <= $3)
GROUP BY entity_type
`

type GetRecordsByEntityTypeParams struct {
	TenantID  pgtype.Text        `json:"tenant_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type GetRecordsByEntityTypeRow struct {
	EntityType pgtype.Text `json:"entity_type"`
	Count      int64       `json:"count"`
}

func (q *Queries) GetRecordsByEntityType(ctx context.Context, arg GetRecordsByEntityTypeParams) ([]GetRecordsByEntityTypeRow, error) {
	rows, err := q.db.Query(ctx, getRecordsByEntityType, arg.TenantID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecordsByEntityTypeRow{}
	for rows.Next() {
		var i GetRecordsByEntityTypeRow
		if err := rows.Scan(&i.EntityType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecordsBySource = `-- name: GetRecordsBySource :many
SELECT source_id, COUNT(*) AS count
FROM ingest_records
WHERE 
    ($1::varchar IS NULL OR tenant_id = $1)
    AND ($2::timestamptz IS NULL OR received_at >= $2)
    AND ($3::timestamptz IS NULL OR received_at <= $3)
GROUP BY source_id
`

type GetRecordsBySourceParams struct {
	TenantID  pgtype.Text        `json:"tenant_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type GetRecordsBySourceRow struct {
	SourceID string `json:"source_id"`
	Count    int64  `json:"count"`
}

func (q *Queries) GetRecordsBySource(ctx context.Context, arg GetRecordsBySourceParams) ([]GetRecordsBySourceRow, error) {
	rows, err := q.db.Query(ctx, getRecordsBySource, arg.TenantID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecordsBySourceRow{}
	for rows.Next() {
		var i GetRecordsBySourceRow
		if err := rows.Scan(&i.SourceID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecordsBySourceType = `-- name: GetRecordsBySourceType :many
SELECT source_type, COUNT(*) AS count
FROM ingest_records
WHERE 
    ($1::varchar IS NULL OR tenant_id = $1)
    AND ($2::timestamptz IS NULL OR received_at >= $2)
    AND ($3::timestamptz IS NULL OR received_at <= $3)
GROUP BY source_type
`

type GetRecordsBySourceTypeParams struct {
	TenantID  pgtype.Text        `json:"tenant_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type GetRecordsBySourceTypeRow struct {
	SourceType string `json:"source_type"`
	Count      int64  `json:"count"`
}

func (q *Queries) GetRecordsBySourceType(ctx context.Context, arg GetRecordsBySourceTypeParams) ([]GetRecordsBySourceTypeRow, error) {
	rows, err := q.db.Query(ctx, getRecordsBySourceType, arg.TenantID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecordsBySourceTypeRow{}
	for rows.Next() {
		var i GetRecordsBySourceTypeRow
		if err := rows.Scan(&i.SourceType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecordsByStatus = `-- name: GetRecordsByStatus :many
SELECT status::text, COUNT(*) AS count
FROM ingest_records
WHERE 
    ($1::varchar IS NULL OR tenant_id = $1)
    AND ($2::timestamptz IS NULL OR received_at >= $2)
    AND ($3::timestamptz IS NULL OR received_at <= $3)
GROUP BY status
`

type GetRecordsByStatusParams struct {
	TenantID  pgtype.Text        `json:"tenant_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type GetRecordsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) GetRecordsByStatus(ctx context.Context, arg GetRecordsByStatusParams) ([]GetRecordsByStatusRow, error) {
	rows, err := q.db.Query(ctx, getRecordsByStatus, arg.TenantID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecordsByStatusRow{}
	for rows.Next() {
		var i GetRecordsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngestRecords = `-- name: ListIngestRecords :many
SELECT id, tenant_id, source_id, source_type, raw_data_id, status, validation_valid, validation_schema_valid, validation_fields_present, validation_fields_missing, validation_anomalies, validation_validator_version, confidence_overall, confidence_source_reliability, confidence_data_completeness, confidence_temporal_freshness, confidence_signature_trust, confidence_factors, entity_type, entity_id, event_ids, rejection_reason, quarantine_id, source_signer, collector_signer, ingest_signer, source_signature_verified, collector_signature_verified, received_at, processed_at, created_at FROM ingest_records
WHERE 
    ($3::varchar IS NULL OR tenant_id = $3)
    AND ($4::varchar IS NULL OR source_id = $4)
    AND ($5::varchar IS NULL OR source_type = $5)
    AND ($6::ingest_status IS NULL OR status = $6)
    AND ($7::varchar IS NULL OR entity_type = $7)
    AND ($8::timestamptz IS NULL OR received_at >= $8)
    AND ($9::timestamptz IS NULL OR received_at <= $9)
ORDER BY received_at DESC
LIMIT $1 OFFSET $2
`

type ListIngestRecordsParams struct {
	Limit      int32              `json:"limit"`
	Offset     int32              `json:"offset"`
	TenantID   pgtype.Text        `json:"tenant_id"`
	SourceID   pgtype.Text        `json:"source_id"`
	SourceType pgtype.Text        `json:"source_type"`
	Status     NullIngestStatus   `json:"status"`
	EntityType pgtype.Text        `json:"entity_type"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) ListIngestRecords(ctx context.Context, arg ListIngestRecordsParams) ([]IngestRecord, error) {
	rows, err := q.db.Query(ctx, listIngestRecords,
		arg.Limit,
		arg.Offset,
		arg.TenantID,
		arg.SourceID,
		arg.SourceType,
		arg.Status,
		arg.EntityType,
		arg.StartTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestRecord{}
	for rows.Next() {
		var i IngestRecord
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceID,
			&i.SourceType,
			&i.RawDataID,
			&i.Status,
			&i.ValidationValid,
			&i.ValidationSchemaValid,
			&i.ValidationFieldsPresent,
			&i.ValidationFieldsMissing,
			&i.ValidationAnomalies,
			&i.ValidationValidatorVersion,
			&i.ConfidenceOverall,
			&i.ConfidenceSourceReliability,
			&i.ConfidenceDataCompleteness,
			&i.ConfidenceTemporalFreshness,
			&i.ConfidenceSignatureTrust,
			&i.ConfidenceFactors,
			&i.EntityType,
			&i.EntityID,
			&i.EventIds,
			&i.RejectionReason,
			&i.QuarantineID,
			&i.SourceSigner,
			&i.CollectorSigner,
			&i.IngestSigner,
			&i.SourceSignatureVerified,
			&i.CollectorSignatureVerified,
			&i.ReceivedAt,
			&i.ProcessedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngestRecordsBySource = `-- name: ListIngestRecordsBySource :many
SELECT id, tenant_id, source_id, source_type, raw_data_id, status, validation_valid, validation_schema_valid, validation_fields_present, validation_fields_missing, validation_anomalies, validation_validator_version, confidence_overall, confidence_source_reliability, confidence_data_completeness, confidence_temporal_freshness, confidence_signature_trust, confidence_factors, entity_type, entity_id, event_ids, rejection_reason, quarantine_id, source_signer, collector_signer, ingest_signer, source_signature_verified, collector_signature_verified, received_at, processed_at, created_at FROM ingest_records
WHERE source_id = $1
    AND ($4::ingest_status IS NULL OR status = $4)
    AND ($5::timestamptz IS NULL OR received_at >= $5)
    AND ($6::timestamptz IS NULL OR received_at <= $6)
ORDER BY received_at DESC
LIMIT $2 OFFSET $3
`

type ListIngestRecordsBySourceParams struct {
	SourceID  string             `json:"source_id"`
	Limit     int32              `json:"limit"`
	Offset    int32              `json:"offset"`
	Status    NullIngestStatus   `json:"status"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) ListIngestRecordsBySource(ctx context.Context, arg ListIngestRecordsBySourceParams) ([]IngestRecord, error) {
	rows, err := q.db.Query(ctx, listIngestRecordsBySource,
		arg.SourceID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.StartTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestRecord{}
	for rows.Next() {
		var i IngestRecord
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceID,
			&i.SourceType,
			&i.RawDataID,
			&i.Status,
			&i.ValidationValid,
			&i.ValidationSchemaValid,
			&i.ValidationFieldsPresent,
			&i.ValidationFieldsMissing,
			&i.ValidationAnomalies,
			&i.ValidationValidatorVersion,
			&i.ConfidenceOverall,
			&i.ConfidenceSourceReliability,
			&i.ConfidenceDataCompleteness,
			&i.ConfidenceTemporalFreshness,
			&i.ConfidenceSignatureTrust,
			&i.ConfidenceFactors,
			&i.EntityType,
			&i.EntityID,
			&i.EventIds,
			&i.RejectionReason,
			&i.QuarantineID,
			&i.SourceSigner,
			&i.CollectorSigner,
			&i.IngestSigner,
			&i.SourceSignatureVerified,
			&i.CollectorSignatureVerified,
			&i.ReceivedAt,
			&i.ProcessedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngestRecord = `-- name: UpdateIngestRecord :exec
UPDATE ingest_records SET
    status = $2,
    validation_valid = $3,
    validation_schema_valid = $4,
    validation_fields_present = $5,
    validation_fields_missing = $6,
    validation_anomalies = $7,
    validation_validator_version = $8,
    confidence_overall = $9,
    confidence_source_reliability = $10,
    confidence_data_completeness = $11,
    confidence_temporal_freshness = $12,
    confidence_signature_trust = $13,
    confidence_factors = $14,
    entity_type = $15,
    entity_id = $16,
    event_ids = $17,
    rejection_reason = $18,
    quarantine_id = $19,
    source_signer = $20,
    collector_signer = $21,
    ingest_signer = $22,
    source_signature_verified = $23,
    collector_signature_verified = $24,
    processed_at = $25
WHERE id = $1
`

type UpdateIngestRecordParams struct {
	ID                          string      `json:"id"`
	Status                      string      `json:"status"`
	ValidationValid             bool        `json:"validation_valid"`
	ValidationSchemaValid       bool        `json:"validation_schema_valid"`
	ValidationFieldsPresent     []string    `json:"validation_fields_present"`
	ValidationFieldsMissing     []string    `json:"validation_fields_missing"`
	ValidationAnomalies         []byte      `json:"validation_anomalies"`
	ValidationValidatorVersion  pgtype.Text `json:"validation_validator_version"`
	ConfidenceOverall           float32     `json:"confidence_overall"`
	ConfidenceSourceReliability float32     `json:"confidence_source_reliability"`
	ConfidenceDataCompleteness  float32     `json:"confidence_data_completeness"`
	ConfidenceTemporalFreshness float32     `json:"confidence_temporal_freshness"`
	ConfidenceSignatureTrust    float32     `json:"confidence_signature_trust"`
	ConfidenceFactors           []byte      `json:"confidence_factors"`
	EntityType                  pgtype.Text `json:"entity_type"`
	EntityID                    pgtype.Text `json:"entity_id"`
	EventIds                    []string    `json:"event_ids"`
	RejectionReason             pgtype.Text `json:"rejection_reason"`
	QuarantineID                pgtype.Text `json:"quarantine_id"`
	SourceSigner                []byte      `json:"source_signer"`
	CollectorSigner             []byte      `json:"collector_signer"`
	IngestSigner                []byte      `json:"ingest_signer"`
	SourceSignatureVerified     pgtype.Bool `json:"source_signature_verified"`
	CollectorSignatureVerified  pgtype.Bool `json:"collector_signature_verified"`
	ProcessedAt                 time.Time   `json:"processed_at"`
}

func (q *Queries) UpdateIngestRecord(ctx context.Context, arg UpdateIngestRecordParams) error {
	_, err := q.db.Exec(ctx, updateIngestRecord,
		arg.ID,
		arg.Status,
		arg.ValidationValid,
		arg.ValidationSchemaValid,
		arg.ValidationFieldsPresent,
		arg.ValidationFieldsMissing,
		arg.ValidationAnomalies,
		arg.ValidationValidatorVersion,
		arg.ConfidenceOverall,
		arg.ConfidenceSourceReliability,
		arg.ConfidenceDataCompleteness,
		arg.ConfidenceTemporalFreshness,
		arg.ConfidenceSignatureTrust,
		arg.ConfidenceFactors,
		arg.EntityType,
		arg.EntityID,
		arg.EventIds,
		arg.RejectionReason,
		arg.QuarantineID,
		arg.SourceSigner,
		arg.CollectorSigner,
		arg.IngestSigner,
		arg.SourceSignatureVerified,
		arg.CollectorSignatureVerified,
		arg.ProcessedAt,
	)
	return err
}
