// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type IngestStatus string

const (
	IngestStatusPending     IngestStatus = "pending"
	IngestStatusAccepted    IngestStatus = "accepted"
	IngestStatusQuarantined IngestStatus = "quarantined"
	IngestStatusRejected    IngestStatus = "rejected"
)

func (e *IngestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IngestStatus(s)
	case string:
		*e = IngestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IngestStatus: %T", src)
	}
	return nil
}

type NullIngestStatus struct {
	IngestStatus IngestStatus `json:"ingest_status"`
	Valid        bool         `json:"valid"` // Valid is true if IngestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIngestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IngestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IngestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIngestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IngestStatus), nil
}

type QuarantineReason string

const (
	QuarantineReasonValidationFailed   QuarantineReason = "validation_failed"
	QuarantineReasonLowConfidence      QuarantineReason = "low_confidence"
	QuarantineReasonAnomalyDetected    QuarantineReason = "anomaly_detected"
	QuarantineReasonSignatureInvalid   QuarantineReason = "signature_invalid"
	QuarantineReasonDuplicateSuspected QuarantineReason = "duplicate_suspected"
	QuarantineReasonManualReview       QuarantineReason = "manual_review"
)

func (e *QuarantineReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuarantineReason(s)
	case string:
		*e = QuarantineReason(s)
	default:
		return fmt.Errorf("unsupported scan type for QuarantineReason: %T", src)
	}
	return nil
}

type NullQuarantineReason struct {
	QuarantineReason QuarantineReason `json:"quarantine_reason"`
	Valid            bool             `json:"valid"` // Valid is true if QuarantineReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuarantineReason) Scan(value interface{}) error {
	if value == nil {
		ns.QuarantineReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuarantineReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuarantineReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuarantineReason), nil
}

type QuarantineResolution string

const (
	QuarantineResolutionPending  QuarantineResolution = "pending"
	QuarantineResolutionApproved QuarantineResolution = "approved"
	QuarantineResolutionModified QuarantineResolution = "modified"
	QuarantineResolutionRejected QuarantineResolution = "rejected"
	QuarantineResolutionExpired  QuarantineResolution = "expired"
)

func (e *QuarantineResolution) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuarantineResolution(s)
	case string:
		*e = QuarantineResolution(s)
	default:
		return fmt.Errorf("unsupported scan type for QuarantineResolution: %T", src)
	}
	return nil
}

type NullQuarantineResolution struct {
	QuarantineResolution QuarantineResolution `json:"quarantine_resolution"`
	Valid                bool                 `json:"valid"` // Valid is true if QuarantineResolution is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuarantineResolution) Scan(value interface{}) error {
	if value == nil {
		ns.QuarantineResolution, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuarantineResolution.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuarantineResolution) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuarantineResolution), nil
}

type IngestRecord struct {
	ID                          string      `json:"id"`
	TenantID                    pgtype.Text `json:"tenant_id"`
	SourceID                    string      `json:"source_id"`
	SourceType                  string      `json:"source_type"`
	RawDataID                   string      `json:"raw_data_id"`
	Status                      string      `json:"status"`
	ValidationValid             bool        `json:"validation_valid"`
	ValidationSchemaValid       bool        `json:"validation_schema_valid"`
	ValidationFieldsPresent     []string    `json:"validation_fields_present"`
	ValidationFieldsMissing     []string    `json:"validation_fields_missing"`
	ValidationAnomalies         []byte      `json:"validation_anomalies"`
	ValidationValidatorVersion  pgtype.Text `json:"validation_validator_version"`
	ConfidenceOverall           float32     `json:"confidence_overall"`
	ConfidenceSourceReliability float32     `json:"confidence_source_reliability"`
	ConfidenceDataCompleteness  float32     `json:"confidence_data_completeness"`
	ConfidenceTemporalFreshness float32     `json:"confidence_temporal_freshness"`
	ConfidenceSignatureTrust    float32     `json:"confidence_signature_trust"`
	ConfidenceFactors           []byte      `json:"confidence_factors"`
	EntityType                  pgtype.Text `json:"entity_type"`
	EntityID                    pgtype.Text `json:"entity_id"`
	EventIds                    []string    `json:"event_ids"`
	RejectionReason             pgtype.Text `json:"rejection_reason"`
	QuarantineID                pgtype.Text `json:"quarantine_id"`
	SourceSigner                []byte      `json:"source_signer"`
	CollectorSigner             []byte      `json:"collector_signer"`
	IngestSigner                []byte      `json:"ingest_signer"`
	SourceSignatureVerified     pgtype.Bool `json:"source_signature_verified"`
	CollectorSignatureVerified  pgtype.Bool `json:"collector_signature_verified"`
	ReceivedAt                  time.Time   `json:"received_at"`
	ProcessedAt                 time.Time   `json:"processed_at"`
	CreatedAt                   time.Time   `json:"created_at"`
}

type QuarantinedRecord struct {
	ID                          string             `json:"id"`
	TenantID                    pgtype.Text        `json:"tenant_id"`
	SourceID                    string             `json:"source_id"`
	SourceType                  string             `json:"source_type"`
	RawDataID                   string             `json:"raw_data_id"`
	IngestRecordID              string             `json:"ingest_record_id"`
	RawData                     []byte             `json:"raw_data"`
	Reason                      string             `json:"reason"`
	ReasonDetail                string             `json:"reason_detail"`
	Anomalies                   []byte             `json:"anomalies"`
	ConfidenceOverall           float32            `json:"confidence_overall"`
	ConfidenceSourceReliability float32            `json:"confidence_source_reliability"`
	ConfidenceDataCompleteness  float32            `json:"confidence_data_completeness"`
	ConfidenceTemporalFreshness float32            `json:"confidence_temporal_freshness"`
	ConfidenceSignatureTrust    float32            `json:"confidence_signature_trust"`
	ConfidenceFactors           []byte             `json:"confidence_factors"`
	Resolution                  string             `json:"resolution"`
	ResolvedBy                  pgtype.Text        `json:"resolved_by"`
	ResolvedByDid               pgtype.Text        `json:"resolved_by_did"`
	ResolutionNotes             pgtype.Text        `json:"resolution_notes"`
	ModifiedData                []byte             `json:"modified_data"`
	IngestSigner                []byte             `json:"ingest_signer"`
	ResolverSigner              []byte             `json:"resolver_signer"`
	QuarantinedAt               time.Time          `json:"quarantined_at"`
	ExpiresAt                   pgtype.Timestamptz `json:"expires_at"`
	ResolvedAt                  pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt                   time.Time          `json:"created_at"`
}

type SourceReliability struct {
	SourceID            string      `json:"source_id"`
	TenantID            pgtype.Text `json:"tenant_id"`
	ReliabilityScore    float32     `json:"reliability_score"`
	TotalRecords        int64       `json:"total_records"`
	AcceptedRecords     int64       `json:"accepted_records"`
	RejectedRecords     int64       `json:"rejected_records"`
	QuarantinedRecords  int64       `json:"quarantined_records"`
	CorroboratedRecords int64       `json:"corroborated_records"`
	DisputedRecords     int64       `json:"disputed_records"`
	CalculatedAt        time.Time   `json:"calculated_at"`
	WindowStart         time.Time   `json:"window_start"`
	WindowEnd           time.Time   `json:"window_end"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
}
