// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quarantined_records.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkUpdateResolution = `-- name: BulkUpdateResolution :exec
UPDATE quarantined_records SET
    resolution = $2,
    resolved_by = $3,
    resolved_by_did = $4,
    resolution_notes = $5,
    resolved_at = $6
WHERE id = ANY($1::varchar[])
`

type BulkUpdateResolutionParams struct {
	Column1         []string           `json:"column_1"`
	Resolution      string             `json:"resolution"`
	ResolvedBy      pgtype.Text        `json:"resolved_by"`
	ResolvedByDid   pgtype.Text        `json:"resolved_by_did"`
	ResolutionNotes pgtype.Text        `json:"resolution_notes"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
}

func (q *Queries) BulkUpdateResolution(ctx context.Context, arg BulkUpdateResolutionParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateResolution,
		arg.Column1,
		arg.Resolution,
		arg.ResolvedBy,
		arg.ResolvedByDid,
		arg.ResolutionNotes,
		arg.ResolvedAt,
	)
	return err
}

const countPendingByTenant = `-- name: CountPendingByTenant :one
SELECT COUNT(*) FROM quarantined_records
WHERE 
    resolution = 'pending'
    AND ($1::varchar IS NULL OR tenant_id = $1)
`

func (q *Queries) CountPendingByTenant(ctx context.Context, tenantID pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQuarantinedRecords = `-- name: CountQuarantinedRecords :one
SELECT COUNT(*) FROM quarantined_records
WHERE 
    ($1::varchar IS NULL OR tenant_id = $1)
    AND ($2::varchar IS NULL OR source_id = $2)
    AND ($3::varchar IS NULL OR source_type = $3)
    AND ($4::quarantine_reason IS NULL OR reason = $4)
    AND ($5::quarantine_resolution IS NULL OR resolution = $5)
    AND ($6::timestamptz IS NULL OR quarantined_at >= $6)
    AND ($7::timestamptz IS NULL OR quarantined_at <= $7)
`

type CountQuarantinedRecordsParams struct {
	TenantID   pgtype.Text              `json:"tenant_id"`
	SourceID   pgtype.Text              `json:"source_id"`
	SourceType pgtype.Text              `json:"source_type"`
	Reason     NullQuarantineReason     `json:"reason"`
	Resolution NullQuarantineResolution `json:"resolution"`
	StartTime  pgtype.Timestamptz       `json:"start_time"`
	EndTime    pgtype.Timestamptz       `json:"end_time"`
}

func (q *Queries) CountQuarantinedRecords(ctx context.Context, arg CountQuarantinedRecordsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countQuarantinedRecords,
		arg.TenantID,
		arg.SourceID,
		arg.SourceType,
		arg.Reason,
		arg.Resolution,
		arg.StartTime,
		arg.EndTime,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQuarantinedRecord = `-- name: CreateQuarantinedRecord :exec
INSERT INTO quarantined_records (
    id, tenant_id, source_id, source_type, raw_data_id, ingest_record_id,
    raw_data,
    reason, reason_detail, anomalies,
    confidence_overall, confidence_source_reliability, confidence_data_completeness,
    confidence_temporal_freshness, confidence_signature_trust, confidence_factors,
    resolution, resolved_by, resolved_by_did, resolution_notes, modified_data,
    ingest_signer, resolver_signer,
    quarantined_at, expires_at, resolved_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7,
    $8, $9, $10,
    $11, $12, $13, $14, $15, $16,
    $17, $18, $19, $20, $21,
    $22, $23,
    $24, $25, $26
)
`

type CreateQuarantinedRecordParams struct {
	ID                          string             `json:"id"`
	TenantID                    pgtype.Text        `json:"tenant_id"`
	SourceID                    string             `json:"source_id"`
	SourceType                  string             `json:"source_type"`
	RawDataID                   string             `json:"raw_data_id"`
	IngestRecordID              string             `json:"ingest_record_id"`
	RawData                     []byte             `json:"raw_data"`
	Reason                      string             `json:"reason"`
	ReasonDetail                string             `json:"reason_detail"`
	Anomalies                   []byte             `json:"anomalies"`
	ConfidenceOverall           float32            `json:"confidence_overall"`
	ConfidenceSourceReliability float32            `json:"confidence_source_reliability"`
	ConfidenceDataCompleteness  float32            `json:"confidence_data_completeness"`
	ConfidenceTemporalFreshness float32            `json:"confidence_temporal_freshness"`
	ConfidenceSignatureTrust    float32            `json:"confidence_signature_trust"`
	ConfidenceFactors           []byte             `json:"confidence_factors"`
	Resolution                  string             `json:"resolution"`
	ResolvedBy                  pgtype.Text        `json:"resolved_by"`
	ResolvedByDid               pgtype.Text        `json:"resolved_by_did"`
	ResolutionNotes             pgtype.Text        `json:"resolution_notes"`
	ModifiedData                []byte             `json:"modified_data"`
	IngestSigner                []byte             `json:"ingest_signer"`
	ResolverSigner              []byte             `json:"resolver_signer"`
	QuarantinedAt               time.Time          `json:"quarantined_at"`
	ExpiresAt                   pgtype.Timestamptz `json:"expires_at"`
	ResolvedAt                  pgtype.Timestamptz `json:"resolved_at"`
}

func (q *Queries) CreateQuarantinedRecord(ctx context.Context, arg CreateQuarantinedRecordParams) error {
	_, err := q.db.Exec(ctx, createQuarantinedRecord,
		arg.ID,
		arg.TenantID,
		arg.SourceID,
		arg.SourceType,
		arg.RawDataID,
		arg.IngestRecordID,
		arg.RawData,
		arg.Reason,
		arg.ReasonDetail,
		arg.Anomalies,
		arg.ConfidenceOverall,
		arg.ConfidenceSourceReliability,
		arg.ConfidenceDataCompleteness,
		arg.ConfidenceTemporalFreshness,
		arg.ConfidenceSignatureTrust,
		arg.ConfidenceFactors,
		arg.Resolution,
		arg.ResolvedBy,
		arg.ResolvedByDid,
		arg.ResolutionNotes,
		arg.ModifiedData,
		arg.IngestSigner,
		arg.ResolverSigner,
		arg.QuarantinedAt,
		arg.ExpiresAt,
		arg.ResolvedAt,
	)
	return err
}

const deleteQuarantinedRecord = `-- name: DeleteQuarantinedRecord :exec
DELETE FROM quarantined_records WHERE id = $1
`

func (q *Queries) DeleteQuarantinedRecord(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteQuarantinedRecord, id)
	return err
}

const findQuarantinedRecordByID = `-- name: FindQuarantinedRecordByID :one
SELECT id, tenant_id, source_id, source_type, raw_data_id, ingest_record_id, raw_data, reason, reason_detail, anomalies, confidence_overall, confidence_source_reliability, confidence_data_completeness, confidence_temporal_freshness, confidence_signature_trust, confidence_factors, resolution, resolved_by, resolved_by_did, resolution_notes, modified_data, ingest_signer, resolver_signer, quarantined_at, expires_at, resolved_at, created_at FROM quarantined_records WHERE id = $1
`

func (q *Queries) FindQuarantinedRecordByID(ctx context.Context, id string) (QuarantinedRecord, error) {
	row := q.db.QueryRow(ctx, findQuarantinedRecordByID, id)
	var i QuarantinedRecord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceID,
		&i.SourceType,
		&i.RawDataID,
		&i.IngestRecordID,
		&i.RawData,
		&i.Reason,
		&i.ReasonDetail,
		&i.Anomalies,
		&i.ConfidenceOverall,
		&i.ConfidenceSourceReliability,
		&i.ConfidenceDataCompleteness,
		&i.ConfidenceTemporalFreshness,
		&i.ConfidenceSignatureTrust,
		&i.ConfidenceFactors,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolvedByDid,
		&i.ResolutionNotes,
		&i.ModifiedData,
		&i.IngestSigner,
		&i.ResolverSigner,
		&i.QuarantinedAt,
		&i.ExpiresAt,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findQuarantinedRecordByIngestRecordID = `-- name: FindQuarantinedRecordByIngestRecordID :one
SELECT id, tenant_id, source_id, source_type, raw_data_id, ingest_record_id, raw_data, reason, reason_detail, anomalies, confidence_overall, confidence_source_reliability, confidence_data_completeness, confidence_temporal_freshness, confidence_signature_trust, confidence_factors, resolution, resolved_by, resolved_by_did, resolution_notes, modified_data, ingest_signer, resolver_signer, quarantined_at, expires_at, resolved_at, created_at FROM quarantined_records WHERE ingest_record_id = $1
`

func (q *Queries) FindQuarantinedRecordByIngestRecordID(ctx context.Context, ingestRecordID string) (QuarantinedRecord, error) {
	row := q.db.QueryRow(ctx, findQuarantinedRecordByIngestRecordID, ingestRecordID)
	var i QuarantinedRecord
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceID,
		&i.SourceType,
		&i.RawDataID,
		&i.IngestRecordID,
		&i.RawData,
		&i.Reason,
		&i.ReasonDetail,
		&i.Anomalies,
		&i.ConfidenceOverall,
		&i.ConfidenceSourceReliability,
		&i.ConfidenceDataCompleteness,
		&i.ConfidenceTemporalFreshness,
		&i.ConfidenceSignatureTrust,
		&i.ConfidenceFactors,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolvedByDid,
		&i.ResolutionNotes,
		&i.ModifiedData,
		&i.IngestSigner,
		&i.ResolverSigner,
		&i.QuarantinedAt,
		&i.ExpiresAt,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getQuarantineByReason = `-- name: GetQuarantineByReason :many
SELECT reason::text, COUNT(*) AS count
FROM quarantined_records
WHERE 
    ($1::varchar IS NULL OR tenant_id = $1)
    AND ($2::timestamptz IS NULL OR quarantined_at >= $2)
    AND ($3::timestamptz IS NULL OR quarantined_at <= $3)
GROUP BY reason
`

type GetQuarantineByReasonParams struct {
	TenantID  pgtype.Text        `json:"tenant_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type GetQuarantineByReasonRow struct {
	Reason string `json:"reason"`
	Count  int64  `json:"count"`
}

func (q *Queries) GetQuarantineByReason(ctx context.Context, arg GetQuarantineByReasonParams) ([]GetQuarantineByReasonRow, error) {
	rows, err := q.db.Query(ctx, getQuarantineByReason, arg.TenantID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetQuarantineByReasonRow{}
	for rows.Next() {
		var i GetQuarantineByReasonRow
		if err := rows.Scan(&i.Reason, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredQuarantinedRecords = `-- name: ListExpiredQuarantinedRecords :many
SELECT id, tenant_id, source_id, source_type, raw_data_id, ingest_record_id, raw_data, reason, reason_detail, anomalies, confidence_overall, confidence_source_reliability, confidence_data_completeness, confidence_temporal_freshness, confidence_signature_trust, confidence_factors, resolution, resolved_by, resolved_by_did, resolution_notes, modified_data, ingest_signer, resolver_signer, quarantined_at, expires_at, resolved_at, created_at FROM quarantined_records
WHERE 
    resolution = 'pending'
    AND expires_at IS NOT NULL
    AND expires_at <= $1
LIMIT $2
`

type ListExpiredQuarantinedRecordsParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListExpiredQuarantinedRecords(ctx context.Context, arg ListExpiredQuarantinedRecordsParams) ([]QuarantinedRecord, error) {
	rows, err := q.db.Query(ctx, listExpiredQuarantinedRecords, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuarantinedRecord{}
	for rows.Next() {
		var i QuarantinedRecord
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceID,
			&i.SourceType,
			&i.RawDataID,
			&i.IngestRecordID,
			&i.RawData,
			&i.Reason,
			&i.ReasonDetail,
			&i.Anomalies,
			&i.ConfidenceOverall,
			&i.ConfidenceSourceReliability,
			&i.ConfidenceDataCompleteness,
			&i.ConfidenceTemporalFreshness,
			&i.ConfidenceSignatureTrust,
			&i.ConfidenceFactors,
			&i.Resolution,
			&i.ResolvedBy,
			&i.ResolvedByDid,
			&i.ResolutionNotes,
			&i.ModifiedData,
			&i.IngestSigner,
			&i.ResolverSigner,
			&i.QuarantinedAt,
			&i.ExpiresAt,
			&i.ResolvedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingQuarantinedRecords = `-- name: ListPendingQuarantinedRecords :many
SELECT id, tenant_id, source_id, source_type, raw_data_id, ingest_record_id, raw_data, reason, reason_detail, anomalies, confidence_overall, confidence_source_reliability, confidence_data_completeness, confidence_temporal_freshness, confidence_signature_trust, confidence_factors, resolution, resolved_by, resolved_by_did, resolution_notes, modified_data, ingest_signer, resolver_signer, quarantined_at, expires_at, resolved_at, created_at FROM quarantined_records
WHERE 
    resolution = 'pending'
    AND ($3::varchar IS NULL OR tenant_id = $3)
ORDER BY 
    CASE reason
        WHEN 'signature_invalid' THEN 1
        WHEN 'validation_failed' THEN 2
        WHEN 'anomaly_detected' THEN 3
        WHEN 'low_confidence' THEN 4
        WHEN 'duplicate_suspected' THEN 5
        WHEN 'manual_review' THEN 6
    END,
    quarantined_at ASC
LIMIT $1 OFFSET $2
`

type ListPendingQuarantinedRecordsParams struct {
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	TenantID pgtype.Text `json:"tenant_id"`
}

func (q *Queries) ListPendingQuarantinedRecords(ctx context.Context, arg ListPendingQuarantinedRecordsParams) ([]QuarantinedRecord, error) {
	rows, err := q.db.Query(ctx, listPendingQuarantinedRecords, arg.Limit, arg.Offset, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuarantinedRecord{}
	for rows.Next() {
		var i QuarantinedRecord
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceID,
			&i.SourceType,
			&i.RawDataID,
			&i.IngestRecordID,
			&i.RawData,
			&i.Reason,
			&i.ReasonDetail,
			&i.Anomalies,
			&i.ConfidenceOverall,
			&i.ConfidenceSourceReliability,
			&i.ConfidenceDataCompleteness,
			&i.ConfidenceTemporalFreshness,
			&i.ConfidenceSignatureTrust,
			&i.ConfidenceFactors,
			&i.Resolution,
			&i.ResolvedBy,
			&i.ResolvedByDid,
			&i.ResolutionNotes,
			&i.ModifiedData,
			&i.IngestSigner,
			&i.ResolverSigner,
			&i.QuarantinedAt,
			&i.ExpiresAt,
			&i.ResolvedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuarantinedRecords = `-- name: ListQuarantinedRecords :many
SELECT id, tenant_id, source_id, source_type, raw_data_id, ingest_record_id, raw_data, reason, reason_detail, anomalies, confidence_overall, confidence_source_reliability, confidence_data_completeness, confidence_temporal_freshness, confidence_signature_trust, confidence_factors, resolution, resolved_by, resolved_by_did, resolution_notes, modified_data, ingest_signer, resolver_signer, quarantined_at, expires_at, resolved_at, created_at FROM quarantined_records
WHERE 
    ($3::varchar IS NULL OR tenant_id = $3)
    AND ($4::varchar IS NULL OR source_id = $4)
    AND ($5::varchar IS NULL OR source_type = $5)
    AND ($6::quarantine_reason IS NULL OR reason = $6)
    AND ($7::quarantine_resolution IS NULL OR resolution = $7)
    AND ($8::timestamptz IS NULL OR quarantined_at >= $8)
    AND ($9::timestamptz IS NULL OR quarantined_at <= $9)
ORDER BY quarantined_at DESC
LIMIT $1 OFFSET $2
`

type ListQuarantinedRecordsParams struct {
	Limit      int32                    `json:"limit"`
	Offset     int32                    `json:"offset"`
	TenantID   pgtype.Text              `json:"tenant_id"`
	SourceID   pgtype.Text              `json:"source_id"`
	SourceType pgtype.Text              `json:"source_type"`
	Reason     NullQuarantineReason     `json:"reason"`
	Resolution NullQuarantineResolution `json:"resolution"`
	StartTime  pgtype.Timestamptz       `json:"start_time"`
	EndTime    pgtype.Timestamptz       `json:"end_time"`
}

func (q *Queries) ListQuarantinedRecords(ctx context.Context, arg ListQuarantinedRecordsParams) ([]QuarantinedRecord, error) {
	rows, err := q.db.Query(ctx, listQuarantinedRecords,
		arg.Limit,
		arg.Offset,
		arg.TenantID,
		arg.SourceID,
		arg.SourceType,
		arg.Reason,
		arg.Resolution,
		arg.StartTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuarantinedRecord{}
	for rows.Next() {
		var i QuarantinedRecord
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceID,
			&i.SourceType,
			&i.RawDataID,
			&i.IngestRecordID,
			&i.RawData,
			&i.Reason,
			&i.ReasonDetail,
			&i.Anomalies,
			&i.ConfidenceOverall,
			&i.ConfidenceSourceReliability,
			&i.ConfidenceDataCompleteness,
			&i.ConfidenceTemporalFreshness,
			&i.ConfidenceSignatureTrust,
			&i.ConfidenceFactors,
			&i.Resolution,
			&i.ResolvedBy,
			&i.ResolvedByDid,
			&i.ResolutionNotes,
			&i.ModifiedData,
			&i.IngestSigner,
			&i.ResolverSigner,
			&i.QuarantinedAt,
			&i.ExpiresAt,
			&i.ResolvedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuarantinedRecord = `-- name: UpdateQuarantinedRecord :exec
UPDATE quarantined_records SET
    resolution = $2,
    resolved_by = $3,
    resolved_by_did = $4,
    resolution_notes = $5,
    modified_data = $6,
    resolver_signer = $7,
    resolved_at = $8
WHERE id = $1
`

type UpdateQuarantinedRecordParams struct {
	ID              string             `json:"id"`
	Resolution      string             `json:"resolution"`
	ResolvedBy      pgtype.Text        `json:"resolved_by"`
	ResolvedByDid   pgtype.Text        `json:"resolved_by_did"`
	ResolutionNotes pgtype.Text        `json:"resolution_notes"`
	ModifiedData    []byte             `json:"modified_data"`
	ResolverSigner  []byte             `json:"resolver_signer"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
}

func (q *Queries) UpdateQuarantinedRecord(ctx context.Context, arg UpdateQuarantinedRecordParams) error {
	_, err := q.db.Exec(ctx, updateQuarantinedRecord,
		arg.ID,
		arg.Resolution,
		arg.ResolvedBy,
		arg.ResolvedByDid,
		arg.ResolutionNotes,
		arg.ModifiedData,
		arg.ResolverSigner,
		arg.ResolvedAt,
	)
	return err
}
