// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: source_reliability.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSourceReliability = `-- name: CountSourceReliability :one
SELECT COUNT(*) FROM source_reliability
WHERE 
    ($1::varchar IS NULL OR tenant_id = $1)
    AND ($2::real IS NULL OR reliability_score >= $2)
    AND ($3::real IS NULL OR reliability_score <= $3)
`

type CountSourceReliabilityParams struct {
	TenantID pgtype.Text   `json:"tenant_id"`
	MinScore pgtype.Float4 `json:"min_score"`
	MaxScore pgtype.Float4 `json:"max_score"`
}

func (q *Queries) CountSourceReliability(ctx context.Context, arg CountSourceReliabilityParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSourceReliability, arg.TenantID, arg.MinScore, arg.MaxScore)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSourceReliability = `-- name: DeleteSourceReliability :exec
DELETE FROM source_reliability WHERE source_id = $1
`

func (q *Queries) DeleteSourceReliability(ctx context.Context, sourceID string) error {
	_, err := q.db.Exec(ctx, deleteSourceReliability, sourceID)
	return err
}

const existsSourceReliability = `-- name: ExistsSourceReliability :one
SELECT EXISTS(SELECT 1 FROM source_reliability WHERE source_id = $1)
`

func (q *Queries) ExistsSourceReliability(ctx context.Context, sourceID string) (bool, error) {
	row := q.db.QueryRow(ctx, existsSourceReliability, sourceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findSourceReliabilityByID = `-- name: FindSourceReliabilityByID :one
SELECT source_id, tenant_id, reliability_score, total_records, accepted_records, rejected_records, quarantined_records, corroborated_records, disputed_records, calculated_at, window_start, window_end, created_at, updated_at FROM source_reliability WHERE source_id = $1
`

func (q *Queries) FindSourceReliabilityByID(ctx context.Context, sourceID string) (SourceReliability, error) {
	row := q.db.QueryRow(ctx, findSourceReliabilityByID, sourceID)
	var i SourceReliability
	err := row.Scan(
		&i.SourceID,
		&i.TenantID,
		&i.ReliabilityScore,
		&i.TotalRecords,
		&i.AcceptedRecords,
		&i.RejectedRecords,
		&i.QuarantinedRecords,
		&i.CorroboratedRecords,
		&i.DisputedRecords,
		&i.CalculatedAt,
		&i.WindowStart,
		&i.WindowEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementAccepted = `-- name: IncrementAccepted :exec
UPDATE source_reliability SET
    total_records = total_records + 1,
    accepted_records = accepted_records + 1,
    calculated_at = NOW(),
    window_end = NOW(),
    updated_at = NOW()
WHERE source_id = $1
`

func (q *Queries) IncrementAccepted(ctx context.Context, sourceID string) error {
	_, err := q.db.Exec(ctx, incrementAccepted, sourceID)
	return err
}

const incrementCorroborated = `-- name: IncrementCorroborated :exec
UPDATE source_reliability SET
    corroborated_records = corroborated_records + 1,
    calculated_at = NOW(),
    updated_at = NOW()
WHERE source_id = $1
`

func (q *Queries) IncrementCorroborated(ctx context.Context, sourceID string) error {
	_, err := q.db.Exec(ctx, incrementCorroborated, sourceID)
	return err
}

const incrementDisputed = `-- name: IncrementDisputed :exec
UPDATE source_reliability SET
    disputed_records = disputed_records + 1,
    calculated_at = NOW(),
    updated_at = NOW()
WHERE source_id = $1
`

func (q *Queries) IncrementDisputed(ctx context.Context, sourceID string) error {
	_, err := q.db.Exec(ctx, incrementDisputed, sourceID)
	return err
}

const incrementQuarantined = `-- name: IncrementQuarantined :exec
UPDATE source_reliability SET
    total_records = total_records + 1,
    quarantined_records = quarantined_records + 1,
    calculated_at = NOW(),
    window_end = NOW(),
    updated_at = NOW()
WHERE source_id = $1
`

func (q *Queries) IncrementQuarantined(ctx context.Context, sourceID string) error {
	_, err := q.db.Exec(ctx, incrementQuarantined, sourceID)
	return err
}

const incrementRejected = `-- name: IncrementRejected :exec
UPDATE source_reliability SET
    total_records = total_records + 1,
    rejected_records = rejected_records + 1,
    calculated_at = NOW(),
    window_end = NOW(),
    updated_at = NOW()
WHERE source_id = $1
`

func (q *Queries) IncrementRejected(ctx context.Context, sourceID string) error {
	_, err := q.db.Exec(ctx, incrementRejected, sourceID)
	return err
}

const listSourceReliability = `-- name: ListSourceReliability :many
SELECT source_id, tenant_id, reliability_score, total_records, accepted_records, rejected_records, quarantined_records, corroborated_records, disputed_records, calculated_at, window_start, window_end, created_at, updated_at FROM source_reliability
WHERE 
    ($3::varchar IS NULL OR tenant_id = $3)
    AND ($4::real IS NULL OR reliability_score >= $4)
    AND ($5::real IS NULL OR reliability_score <= $5)
ORDER BY reliability_score DESC
LIMIT $1 OFFSET $2
`

type ListSourceReliabilityParams struct {
	Limit    int32         `json:"limit"`
	Offset   int32         `json:"offset"`
	TenantID pgtype.Text   `json:"tenant_id"`
	MinScore pgtype.Float4 `json:"min_score"`
	MaxScore pgtype.Float4 `json:"max_score"`
}

func (q *Queries) ListSourceReliability(ctx context.Context, arg ListSourceReliabilityParams) ([]SourceReliability, error) {
	rows, err := q.db.Query(ctx, listSourceReliability,
		arg.Limit,
		arg.Offset,
		arg.TenantID,
		arg.MinScore,
		arg.MaxScore,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SourceReliability{}
	for rows.Next() {
		var i SourceReliability
		if err := rows.Scan(
			&i.SourceID,
			&i.TenantID,
			&i.ReliabilityScore,
			&i.TotalRecords,
			&i.AcceptedRecords,
			&i.RejectedRecords,
			&i.QuarantinedRecords,
			&i.CorroboratedRecords,
			&i.DisputedRecords,
			&i.CalculatedAt,
			&i.WindowStart,
			&i.WindowEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreliableSources = `-- name: ListUnreliableSources :many
SELECT source_id, tenant_id, reliability_score, total_records, accepted_records, rejected_records, quarantined_records, corroborated_records, disputed_records, calculated_at, window_start, window_end, created_at, updated_at FROM source_reliability
WHERE 
    reliability_score < $1
    AND ($4::varchar IS NULL OR tenant_id = $4)
ORDER BY reliability_score ASC
LIMIT $2 OFFSET $3
`

type ListUnreliableSourcesParams struct {
	ReliabilityScore float32     `json:"reliability_score"`
	Limit            int32       `json:"limit"`
	Offset           int32       `json:"offset"`
	TenantID         pgtype.Text `json:"tenant_id"`
}

func (q *Queries) ListUnreliableSources(ctx context.Context, arg ListUnreliableSourcesParams) ([]SourceReliability, error) {
	rows, err := q.db.Query(ctx, listUnreliableSources,
		arg.ReliabilityScore,
		arg.Limit,
		arg.Offset,
		arg.TenantID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SourceReliability{}
	for rows.Next() {
		var i SourceReliability
		if err := rows.Scan(
			&i.SourceID,
			&i.TenantID,
			&i.ReliabilityScore,
			&i.TotalRecords,
			&i.AcceptedRecords,
			&i.RejectedRecords,
			&i.QuarantinedRecords,
			&i.CorroboratedRecords,
			&i.DisputedRecords,
			&i.CalculatedAt,
			&i.WindowStart,
			&i.WindowEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetSourceReliability = `-- name: ResetSourceReliability :exec
UPDATE source_reliability SET
    reliability_score = 0.5,
    total_records = 0,
    accepted_records = 0,
    rejected_records = 0,
    quarantined_records = 0,
    corroborated_records = 0,
    disputed_records = 0,
    window_start = $2,
    window_end = $2,
    calculated_at = NOW(),
    updated_at = NOW()
WHERE source_id = $1
`

type ResetSourceReliabilityParams struct {
	SourceID    string    `json:"source_id"`
	WindowStart time.Time `json:"window_start"`
}

func (q *Queries) ResetSourceReliability(ctx context.Context, arg ResetSourceReliabilityParams) error {
	_, err := q.db.Exec(ctx, resetSourceReliability, arg.SourceID, arg.WindowStart)
	return err
}

const updateSourceReliability = `-- name: UpdateSourceReliability :exec
UPDATE source_reliability SET
    reliability_score = $2,
    total_records = $3,
    accepted_records = $4,
    rejected_records = $5,
    quarantined_records = $6,
    corroborated_records = $7,
    disputed_records = $8,
    calculated_at = $9,
    window_start = $10,
    window_end = $11,
    updated_at = NOW()
WHERE source_id = $1
`

type UpdateSourceReliabilityParams struct {
	SourceID            string    `json:"source_id"`
	ReliabilityScore    float32   `json:"reliability_score"`
	TotalRecords        int64     `json:"total_records"`
	AcceptedRecords     int64     `json:"accepted_records"`
	RejectedRecords     int64     `json:"rejected_records"`
	QuarantinedRecords  int64     `json:"quarantined_records"`
	CorroboratedRecords int64     `json:"corroborated_records"`
	DisputedRecords     int64     `json:"disputed_records"`
	CalculatedAt        time.Time `json:"calculated_at"`
	WindowStart         time.Time `json:"window_start"`
	WindowEnd           time.Time `json:"window_end"`
}

func (q *Queries) UpdateSourceReliability(ctx context.Context, arg UpdateSourceReliabilityParams) error {
	_, err := q.db.Exec(ctx, updateSourceReliability,
		arg.SourceID,
		arg.ReliabilityScore,
		arg.TotalRecords,
		arg.AcceptedRecords,
		arg.RejectedRecords,
		arg.QuarantinedRecords,
		arg.CorroboratedRecords,
		arg.DisputedRecords,
		arg.CalculatedAt,
		arg.WindowStart,
		arg.WindowEnd,
	)
	return err
}

const upsertSourceReliability = `-- name: UpsertSourceReliability :exec
INSERT INTO source_reliability (
    source_id, tenant_id,
    reliability_score,
    total_records, accepted_records, rejected_records, quarantined_records,
    corroborated_records, disputed_records,
    calculated_at, window_start, window_end,
    created_at, updated_at
) VALUES (
    $1, $2,
    $3,
    $4, $5, $6, $7,
    $8, $9,
    $10, $11, $12,
    NOW(), NOW()
)
ON CONFLICT (source_id) DO UPDATE SET
    tenant_id = EXCLUDED.tenant_id,
    reliability_score = EXCLUDED.reliability_score,
    total_records = EXCLUDED.total_records,
    accepted_records = EXCLUDED.accepted_records,
    rejected_records = EXCLUDED.rejected_records,
    quarantined_records = EXCLUDED.quarantined_records,
    corroborated_records = EXCLUDED.corroborated_records,
    disputed_records = EXCLUDED.disputed_records,
    calculated_at = EXCLUDED.calculated_at,
    window_start = EXCLUDED.window_start,
    window_end = EXCLUDED.window_end,
    updated_at = NOW()
`

type UpsertSourceReliabilityParams struct {
	SourceID            string      `json:"source_id"`
	TenantID            pgtype.Text `json:"tenant_id"`
	ReliabilityScore    float32     `json:"reliability_score"`
	TotalRecords        int64       `json:"total_records"`
	AcceptedRecords     int64       `json:"accepted_records"`
	RejectedRecords     int64       `json:"rejected_records"`
	QuarantinedRecords  int64       `json:"quarantined_records"`
	CorroboratedRecords int64       `json:"corroborated_records"`
	DisputedRecords     int64       `json:"disputed_records"`
	CalculatedAt        time.Time   `json:"calculated_at"`
	WindowStart         time.Time   `json:"window_start"`
	WindowEnd           time.Time   `json:"window_end"`
}

func (q *Queries) UpsertSourceReliability(ctx context.Context, arg UpsertSourceReliabilityParams) error {
	_, err := q.db.Exec(ctx, upsertSourceReliability,
		arg.SourceID,
		arg.TenantID,
		arg.ReliabilityScore,
		arg.TotalRecords,
		arg.AcceptedRecords,
		arg.RejectedRecords,
		arg.QuarantinedRecords,
		arg.CorroboratedRecords,
		arg.DisputedRecords,
		arg.CalculatedAt,
		arg.WindowStart,
		arg.WindowEnd,
	)
	return err
}
