// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.0
// source: analytics.proto

package analyticsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetSystemStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     int64                  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemStatsRequest) Reset() {
	*x = GetSystemStatsRequest{}
	mi := &file_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemStatsRequest) ProtoMessage() {}

func (x *GetSystemStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemStatsRequest.ProtoReflect.Descriptor instead.
func (*GetSystemStatsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetSystemStatsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetSystemStatsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type GetSystemStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalRequests    int32                  `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	TotalErrors      int32                  `protobuf:"varint,2,opt,name=total_errors,json=totalErrors,proto3" json:"total_errors,omitempty"`
	AverageLatencyMs float32                `protobuf:"fixed32,3,opt,name=average_latency_ms,json=averageLatencyMs,proto3" json:"average_latency_ms,omitempty"`
	Timestamp        int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSystemStatsResponse) Reset() {
	*x = GetSystemStatsResponse{}
	mi := &file_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemStatsResponse) ProtoMessage() {}

func (x *GetSystemStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemStatsResponse.ProtoReflect.Descriptor instead.
func (*GetSystemStatsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetSystemStatsResponse) GetTotalRequests() int32 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *GetSystemStatsResponse) GetTotalErrors() int32 {
	if x != nil {
		return x.TotalErrors
	}
	return 0
}

func (x *GetSystemStatsResponse) GetAverageLatencyMs() float32 {
	if x != nil {
		return x.AverageLatencyMs
	}
	return 0
}

func (x *GetSystemStatsResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\fanalytics.v1\"\x0f\n" +
	"\rHealthRequest\"\\\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"Q\n" +
	"\x15GetSystemStatsRequest\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\"\xae\x01\n" +
	"\x16GetSystemStatsResponse\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x05R\rtotalRequests\x12!\n" +
	"\ftotal_errors\x18\x02 \x01(\x05R\vtotalErrors\x12,\n" +
	"\x12average_latency_ms\x18\x03 \x01(\x02R\x10averageLatencyMs\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp2\xb4\x01\n" +
	"\x10AnalyticsService\x12C\n" +
	"\x06Health\x12\x1b.analytics.v1.HealthRequest\x1a\x1c.analytics.v1.HealthResponse\x12[\n" +
	"\x0eGetSystemStats\x12#.analytics.v1.GetSystemStatsRequest\x1a$.analytics.v1.GetSystemStatsResponseB:Z8github.com/0xsj/scout/api/proto/analytics/v1;analyticsv1b\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_analytics_proto_goTypes = []any{
	(*HealthRequest)(nil),          // 0: analytics.v1.HealthRequest
	(*HealthResponse)(nil),         // 1: analytics.v1.HealthResponse
	(*GetSystemStatsRequest)(nil),  // 2: analytics.v1.GetSystemStatsRequest
	(*GetSystemStatsResponse)(nil), // 3: analytics.v1.GetSystemStatsResponse
}
var file_analytics_proto_depIdxs = []int32{
	0, // 0: analytics.v1.AnalyticsService.Health:input_type -> analytics.v1.HealthRequest
	2, // 1: analytics.v1.AnalyticsService.GetSystemStats:input_type -> analytics.v1.GetSystemStatsRequest
	1, // 2: analytics.v1.AnalyticsService.Health:output_type -> analytics.v1.HealthResponse
	3, // 3: analytics.v1.AnalyticsService.GetSystemStats:output_type -> analytics.v1.GetSystemStatsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
