apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: scout
data:
  ENV: "development"
  LOG_LEVEL: "debug"
  POSTGRES_HOST: "postgres.scout.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "scout"
  POSTGRES_DB: "scout"
  REDIS_HOST: "redis.scout.svc.cluster.local"
  REDIS_PORT: "6379"
  NATS_URL: "nats://nats.scout.svc.cluster.local:4222"
  RABBITMQ_URL: "amqp://scout:scout_dev_password@rabbitmq.scout.svc.cluster.local:5672/"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.scout.svc.cluster.local:4317"
  JAEGER_ENDPOINT: "http://jaeger.scout.svc.cluster.local:14268/api/traces"