apiVersion: v1
kind: Service
metadata:
  name: tools
  namespace: scout
  labels:
    app: tools
spec:
  type: NodePort
  selector:
    app: tools
    component: worker
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      nodePort: 30083
      protocol: TCP